In [302]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

In [303]:
X = np.array([
    [
        (i * j) * (1 + np.random.uniform(-0.1, 0.1))  # ±10% noise
        for j in range(1, 11)
    ]
    for i in range(1, 5)
]).T
X
X.shape  # d > n (can use alternate PCA algorithm, K = X'X)

X = X - X.mean(axis=1, keepdims=True)  # center the data
X

array([[ 1.0436,  1.8459,  2.7533,  3.6286],
       [ 1.972 ,  3.6267,  5.9101,  7.8244],
       [ 3.0218,  5.9448,  9.8066, 12.6097],
       [ 4.3346,  7.4717, 11.6256, 16.5834],
       [ 5.3552,  9.5692, 15.3776, 18.6255],
       [ 6.2027, 13.0449, 17.5599, 25.0305],
       [ 6.3487, 12.6581, 20.1969, 27.2544],
       [ 8.1401, 16.2427, 22.4773, 29.3038],
       [ 8.7821, 18.4166, 25.9021, 38.8636],
       [10.6757, 20.4236, 27.507 , 42.105 ]])

(10, 4)

array([[ -1.2743,  -0.4719,   0.4354,   1.3108],
       [ -2.8613,  -1.2066,   1.0768,   2.9911],
       [ -4.8239,  -1.9009,   1.9609,   4.764 ],
       [ -5.6692,  -2.5321,   1.6217,   6.5796],
       [ -6.8767,  -2.6627,   3.1457,   6.3936],
       [ -9.2569,  -2.4146,   2.1004,   9.571 ],
       [-10.2658,  -3.9564,   3.5824,  10.6398],
       [-10.9009,  -2.7983,   3.4363,  10.2628],
       [-14.209 ,  -4.5745,   2.911 ,  15.8725],
       [-14.5021,  -4.7542,   2.3291,  16.9272]])

In [304]:
X.T.shape, X.shape
K = X.T @ X
K.shape  # K is n * n matrix

((4, 10), (10, 4))

(4, 4)

In [305]:
eigenvalues, eigenvectors = np.linalg.eig(K)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]

eigenvalues
eigenvectors

np.cumsum(eigenvalues) / sum(eigenvalues)

array([1940.8799,   10.1291,    2.0544,    0.    ])

array([[ 0.6554,  0.2153, -0.1659, -0.7047],
       [-0.2141, -0.1793,  0.8466, -0.4531],
       [-0.5241,  0.8195, -0.0763, -0.2191],
       [ 0.5   ,  0.5   ,  0.5   ,  0.5   ]])

array([0.9938, 0.9989, 1.    , 1.    ])

In [306]:
beta_k = eigenvectors
n_lambda_k = eigenvalues

In [307]:
alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)
alpha_k.shape

(4, 4)

In [308]:
X.shape, alpha_k.shape
W_k = X @ alpha_k
W_k.shape

((10, 4), (4, 4))

(10, 4)

In [309]:
W_k = W_k / np.linalg.norm(W_k, axis=0)
W_k

array([[0.0422, 0.0422, 0.0422, 0.0422],
       [0.0962, 0.0962, 0.0962, 0.0962],
       [0.1533, 0.1533, 0.1533, 0.1533],
       [0.2117, 0.2117, 0.2117, 0.2117],
       [0.2057, 0.2057, 0.2057, 0.2057],
       [0.3079, 0.3079, 0.3079, 0.3079],
       [0.3423, 0.3423, 0.3423, 0.3423],
       [0.3302, 0.3302, 0.3302, 0.3302],
       [0.5107, 0.5107, 0.5107, 0.5107],
       [0.5446, 0.5446, 0.5446, 0.5446]])

In [310]:
n = X.shape[1]
C = X @ X.T / n
C.shape

(10, 10)

In [311]:
_, eigenvectors = np.linalg.eigh(C)
eigenvectors

array([[ 0.0397, -0.003 , -0.0071,  0.054 ,  0.2986,  0.9447, -0.0968,
         0.0274, -0.0415, -0.0439],
       [ 0.8234, -0.0917,  0.147 ,  0.1017,  0.4267, -0.1993, -0.1002,
         0.1582, -0.121 , -0.1004],
       [ 0.1427, -0.2425, -0.673 , -0.5491, -0.0793,  0.0387,  0.178 ,
         0.1556, -0.2749, -0.1646],
       [-0.4071,  0.405 , -0.0823, -0.0985,  0.5923, -0.194 , -0.0604,
         0.4669, -0.0186, -0.2081],
       [-0.3205, -0.6214,  0.1794,  0.316 ,  0.0346, -0.0637, -0.0854,
         0.1527, -0.5391, -0.2294],
       [-0.0082,  0.0802, -0.4154,  0.5294,  0.2274, -0.0585,  0.4504,
        -0.4294,  0.0452, -0.3105],
       [ 0.164 ,  0.484 ,  0.1762,  0.1536, -0.4918,  0.1283,  0.2642,
         0.3255, -0.3516, -0.3557],
       [-0.0487,  0.1957,  0.2932, -0.4309,  0.138 , -0.0423, -0.1475,
        -0.6342, -0.3439, -0.3529],
       [ 0.0433,  0.0163, -0.284 ,  0.168 , -0.2404, -0.0218, -0.7129,
         0.0012,  0.2719, -0.4986],
       [-0.0189, -0.3216,  0.3409, -0