In [83]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

In [84]:
X = np.array([
    [
        (i * j) * (1 + np.random.uniform(-0.1, 0.1))  # ±10% noise
        for j in range(1, 11)
    ]
    for i in range(1, 5)
]).T
X
X.shape  # d > n (can use alternate PCA algorithm, K = X'X)

X = X - X.mean(axis=1, keepdims=True)  # center the data
X

array([[ 1.0263,  2.0345,  3.1033,  3.6507],
       [ 2.1944,  3.6023,  6.0037,  7.6051],
       [ 2.9654,  5.909 ,  9.1364, 10.8558],
       [ 3.9577,  8.7099, 11.9545, 16.6211],
       [ 5.0662, 10.2668, 14.13  , 20.3439],
       [ 6.5419, 11.7068, 18.9822, 24.1266],
       [ 6.4874, 14.2287, 20.6424, 27.8974],
       [ 7.943 , 15.9332, 25.2059, 33.9629],
       [ 9.8337, 19.4803, 28.8729, 35.0576],
       [ 9.157 , 20.9904, 28.0486, 38.8383]])

(10, 4)

array([[ -1.4274,  -0.4192,   0.6496,   1.197 ],
       [ -2.657 ,  -1.249 ,   1.1523,   2.7537],
       [ -4.2513,  -1.3077,   1.9198,   3.6392],
       [ -6.3531,  -1.6009,   1.6437,   6.3103],
       [ -7.3855,  -2.1849,   1.6783,   7.8922],
       [ -8.7975,  -3.6326,   3.6428,   8.7872],
       [-10.8266,  -3.0853,   3.3284,  10.5834],
       [-12.8182,  -4.828 ,   4.4446,  13.2016],
       [-13.4774,  -3.8308,   5.5617,  11.7465],
       [-15.1016,  -3.2682,   3.7901,  14.5797]])

In [85]:
X.T.shape, X.shape
K = X.T @ X
K.shape  # K is n * n matrix

((4, 10), (10, 4))

(4, 4)

In [86]:
eigenvalues, eigenvectors = np.linalg.eig(K)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]

eigenvalues
eigenvectors

np.cumsum(eigenvalues) / sum(eigenvalues)

array([1901.8288,    6.7627,    3.0353,   -0.    ])

array([[ 0.684 ,  0.2039, -0.2246, -0.6634],
       [-0.0604,  0.4938, -0.7906,  0.3571],
       [ 0.5277, -0.6816, -0.2731,  0.427 ],
       [-0.5   , -0.5   , -0.5   , -0.5   ]])

array([0.9949, 0.9984, 1.    , 1.    ])

In [87]:
beta_k = eigenvectors
n_lambda_k = eigenvalues

In [88]:
alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)
alpha_k.shape

C:\Users\k26ra\AppData\Local\Temp\ipykernel_19496\109447986.py:1: RuntimeWarning: invalid value encountered in sqrt
  alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)


(4, 4)

In [89]:
X.shape, alpha_k.shape
W_k = X @ alpha_k
W_k.shape

((10, 4), (4, 4))

(10, 4)

In [90]:
W_k = W_k / np.linalg.norm(W_k, axis=0)
W_k

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [91]:
n = X.shape[1]
C = X @ X.T / n
C.shape

(10, 10)

In [92]:
_, eigenvectors = np.linalg.eigh(C)
eigenvectors

array([[-0.9902, -0.0086, -0.0131, -0.0118, -0.0083,  0.0007,  0.0691,
         0.0768, -0.0796, -0.0459],
       [-0.0674,  0.0282,  0.0932,  0.1699,  0.0695, -0.0509, -0.9418,
        -0.1782, -0.1476, -0.0953],
       [ 0.0369,  0.1787,  0.606 , -0.4442, -0.035 , -0.5408,  0.0247,
         0.1851, -0.2334, -0.138 ],
       [-0.0069,  0.3679,  0.0596,  0.5465, -0.637 , -0.2503,  0.0692,
         0.009 ,  0.2105, -0.2116],
       [-0.0336,  0.3102, -0.4639, -0.6123, -0.1788, -0.0872, -0.1244,
        -0.289 ,  0.3303, -0.2548],
       [ 0.0319, -0.4204,  0.1629, -0.167 , -0.5313,  0.3496,  0.0688,
        -0.3391, -0.3861, -0.3074],
       [ 0.0011,  0.5119,  0.3777,  0.0068,  0.2556,  0.6194,  0.0591,
         0.0001,  0.1072, -0.3624],
       [ 0.0039, -0.0481, -0.0879,  0.2665,  0.4494, -0.3546,  0.263 ,
        -0.5452, -0.1572, -0.4473],
       [ 0.1069,  0.1019, -0.4585,  0.0339,  0.0244,  0.0174, -0.0307,
         0.5764, -0.492 , -0.4366],
       [-0.0037, -0.5331,  0.1341,  0

# chatgpt

In [93]:
C = (1 / X.shape[1]) * X @ X.T
eigvals1, eigvecs1 = np.linalg.eigh(C)  # shape: (10, 10)
eigvals1 = eigvals1[::-1]
eigvecs1 = eigvecs1[:, ::-1]  # descending order

eigvals1
eigvecs1

array([475.4572,   1.6907,   0.7588,   0.    ,   0.    ,   0.    ,
        -0.    ,  -0.    ,  -0.    ,  -0.    ])

array([[-0.0459, -0.0796,  0.0768,  0.0691,  0.0007, -0.0083, -0.0118,
        -0.0131, -0.0086, -0.9902],
       [-0.0953, -0.1476, -0.1782, -0.9418, -0.0509,  0.0695,  0.1699,
         0.0932,  0.0282, -0.0674],
       [-0.138 , -0.2334,  0.1851,  0.0247, -0.5408, -0.035 , -0.4442,
         0.606 ,  0.1787,  0.0369],
       [-0.2116,  0.2105,  0.009 ,  0.0692, -0.2503, -0.637 ,  0.5465,
         0.0596,  0.3679, -0.0069],
       [-0.2548,  0.3303, -0.289 , -0.1244, -0.0872, -0.1788, -0.6123,
        -0.4639,  0.3102, -0.0336],
       [-0.3074, -0.3861, -0.3391,  0.0688,  0.3496, -0.5313, -0.167 ,
         0.1629, -0.4204,  0.0319],
       [-0.3624,  0.1072,  0.0001,  0.0591,  0.6194,  0.2556,  0.0068,
         0.3777,  0.5119,  0.0011],
       [-0.4473, -0.1572, -0.5452,  0.263 , -0.3546,  0.4494,  0.2665,
        -0.0879, -0.0481,  0.0039],
       [-0.4366, -0.492 ,  0.5764, -0.0307,  0.0174,  0.0244,  0.0339,
        -0.4585,  0.1019,  0.1069],
       [-0.4935,  0.5802,  0.3163, -0

In [94]:
K = (1 / X.shape[1]) * X.T @ X
eigvals2, eigvecs2 = np.linalg.eigh(K)  # shape: (4, 4)
eigvals2 = eigvals2[::-1]
eigvecs2 = eigvecs2[:, ::-1]

# Recover eigenvectors of C
eigvecs_C = (X @ eigvecs2) / np.sqrt(eigvals2)  # shape: (10, 4)

# Normalize each column (principal component)
eigvecs_C /= np.linalg.norm(eigvecs_C, axis=0)

eigvecs_C

C:\Users\k26ra\AppData\Local\Temp\ipykernel_19496\1132394845.py:7: RuntimeWarning: invalid value encountered in sqrt
  eigvecs_C = (X @ eigvecs2) / np.sqrt(eigvals2)  # shape: (10, 4)


array([[ 0.0459, -0.0796, -0.0768,     nan],
       [ 0.0953, -0.1476,  0.1782,     nan],
       [ 0.138 , -0.2334, -0.1851,     nan],
       [ 0.2116,  0.2105, -0.009 ,     nan],
       [ 0.2548,  0.3303,  0.289 ,     nan],
       [ 0.3074, -0.3861,  0.3391,     nan],
       [ 0.3624,  0.1072, -0.0001,     nan],
       [ 0.4473, -0.1572,  0.5452,     nan],
       [ 0.4366, -0.492 , -0.5764,     nan],
       [ 0.4935,  0.5802, -0.3163,     nan]])

In [95]:
eigvecs1[:, :4]
eigvecs_C

array([[-0.0459, -0.0796,  0.0768,  0.0691],
       [-0.0953, -0.1476, -0.1782, -0.9418],
       [-0.138 , -0.2334,  0.1851,  0.0247],
       [-0.2116,  0.2105,  0.009 ,  0.0692],
       [-0.2548,  0.3303, -0.289 , -0.1244],
       [-0.3074, -0.3861, -0.3391,  0.0688],
       [-0.3624,  0.1072,  0.0001,  0.0591],
       [-0.4473, -0.1572, -0.5452,  0.263 ],
       [-0.4366, -0.492 ,  0.5764, -0.0307],
       [-0.4935,  0.5802,  0.3163, -0.0944]])

array([[ 0.0459, -0.0796, -0.0768,     nan],
       [ 0.0953, -0.1476,  0.1782,     nan],
       [ 0.138 , -0.2334, -0.1851,     nan],
       [ 0.2116,  0.2105, -0.009 ,     nan],
       [ 0.2548,  0.3303,  0.289 ,     nan],
       [ 0.3074, -0.3861,  0.3391,     nan],
       [ 0.3624,  0.1072, -0.0001,     nan],
       [ 0.4473, -0.1572,  0.5452,     nan],
       [ 0.4366, -0.492 , -0.5764,     nan],
       [ 0.4935,  0.5802, -0.3163,     nan]])

In [96]:
eigvals1[:4]
eigvals2

array([475.4572,   1.6907,   0.7588,   0.    ])

array([475.4572,   1.6907,   0.7588,  -0.    ])

In [97]:
import numpy as np

# Step 1: Generate data
X = np.array([
    [
        (i * j) * (1 + np.random.uniform(-0.1, 0.1))  # ±10% noise
        for j in range(1, 11)
    ]
    for i in range(1, 5)
]).T  # Shape: (10, 4)

print("Original X shape:", X.shape)

# Step 2: Center the data
X_centered = X - X.mean(axis=1, keepdims=True)

# === Approach 1: Standard PCA (when d < n but still works here) ===
C = (1 / X_centered.shape[1]) * X_centered @ X_centered.T  # Covariance matrix
eigvals_C, eigvecs_C = np.linalg.eigh(C)  # eigh gives sorted ascending
eigvals_C = eigvals_C[::-1]
eigvecs_C = eigvecs_C[:, ::-1]

print("\n--- Standard PCA ---")
print("Eigenvalues (C):")
print(eigvals_C)
print("First 4 eigenvectors (C):")
print(eigvecs_C[:, :4])

# === Approach 2: Efficient PCA (when d > n) ===
K = (1 / X_centered.shape[1]) * X_centered.T @ X_centered  # Inner product matrix
eigvals_K, eigvecs_K = np.linalg.eigh(K)
eigvals_K = eigvals_K[::-1]
eigvecs_K = eigvecs_K[:, ::-1]

# Recover eigenvectors of C
eigvecs_from_K = (X_centered @ eigvecs_K) / np.sqrt(eigvals_K)

# Normalize eigenvectors
eigvecs_from_K /= np.linalg.norm(eigvecs_from_K, axis=0)

print("\n--- Efficient PCA via dual trick ---")
print("Eigenvalues (from K):")
print(eigvals_K)
print("Recovered eigenvectors (of C):")
print(eigvecs_from_K)

# === Comparison ===
print("\n--- Comparison ---")
print("Difference in eigenvalues:")
print(np.abs(eigvals_C[:4] - eigvals_K))
print("Cosine similarity of each eigenvector column:")
cos_sim = np.sum(eigvecs_C[:, :4] * eigvecs_from_K, axis=0)
print(np.abs(cos_sim))  # Close to 1 means match up to sign

Original X shape: (10, 4)

--- Standard PCA ---
Eigenvalues (C):
[457.4049   2.3596   0.5278   0.       0.       0.       0.      -0.
  -0.      -0.    ]
First 4 eigenvectors (C):
[[-0.048  -0.0175 -0.066  -0.995 ]
 [-0.1054 -0.0281 -0.139  -0.0346]
 [-0.1613  0.1135  0.3561 -0.0228]
 [-0.2344 -0.0669 -0.133   0.0262]
 [-0.2574 -0.3954 -0.5929  0.0504]
 [-0.3267  0.5192  0.2188 -0.0235]
 [-0.3444  0.3908 -0.0235  0.0147]
 [-0.4541 -0.6192  0.5588 -0.0056]
 [-0.4261  0.0375 -0.0208  0.0331]
 [-0.4756  0.1345 -0.3452  0.0569]]

--- Efficient PCA via dual trick ---
Eigenvalues (from K):
[457.4049   2.3596   0.5278   0.    ]
Recovered eigenvectors (of C):
[[ 0.048  -0.0175 -0.066  -0.0634]
 [ 0.1054 -0.0281 -0.139  -0.1339]
 [ 0.1613  0.1135  0.3561  0.3393]
 [ 0.2344 -0.0669 -0.133  -0.1322]
 [ 0.2574 -0.3954 -0.5929 -0.5572]
 [ 0.3267  0.5192  0.2188  0.15  ]
 [ 0.3444  0.3908 -0.0235 -0.0857]
 [ 0.4541 -0.6192  0.5588  0.6144]
 [ 0.4261  0.0375 -0.0208  0.    ]
 [ 0.4756  0.1345 -0.3452