In [455]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

In [456]:
np.random.seed(1)

X = np.array([
    [
        (i * j) * (1 + np.random.uniform(-0.1, 0.1))  # ±10% noise
        for j in range(1, 11)
    ]
    for i in range(1, 5)
]).T

X
X.shape  # d > n (can use alternate PCA algorithm, K = X'X)

array([[ 0.9834,  1.9677,  3.1804,  3.6787],
       [ 2.0881,  4.1482,  6.5619,  7.8738],
       [ 2.7001,  5.6453,  8.6642, 13.0989],
       [ 3.8419,  8.605 , 12.4616, 16.1061],
       [ 4.6468,  9.0548, 16.1292, 20.7675],
       [ 5.5108, 12.4091, 19.4206, 23.1145],
       [ 6.5608, 13.7685, 19.2572, 29.0444],
       [ 7.7529, 16.1878, 21.7875, 34.1416],
       [ 8.8142, 16.7054, 25.2171, 32.5317],
       [10.0776, 18.7924, 32.2689, 42.0012]])

(10, 4)

In [457]:
# X.mean(axis=1, keepdims=True)
X = X - X.mean(axis=1, keepdims=True)  # center the data
X

array([[ -1.4691,  -0.4849,   0.7279,   1.2261],
       [ -3.0799,  -1.0198,   1.3939,   2.7058],
       [ -4.8271,  -1.8818,   1.137 ,   5.5718],
       [ -6.4118,  -1.6487,   2.2079,   5.8525],
       [ -8.0028,  -3.5948,   3.4796,   8.118 ],
       [ -9.6029,  -2.7046,   4.3068,   8.0007],
       [-10.5969,  -3.3892,   2.0995,  11.8867],
       [-12.2145,  -3.7796,   1.82  ,  14.1742],
       [-12.0029,  -4.1117,   4.4   ,  11.7146],
       [-15.7074,  -6.9926,   6.4838,  16.2161]])

# PCA alternate algo (K = X'X)

In [458]:
X.T.shape, X.shape
K = X.T @ X
K.shape  # K is n * n matrix

((4, 10), (10, 4))

(4, 4)

In [459]:
eigenvalues, eigenvectors = np.linalg.eig(K)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]
# eigenvalues = np.where(np.isclose(eigenvalues, 0), 0, eigenvalues)

eigenvalues
eigenvectors

array([2037.9956,   17.4369,    3.36  ,   -0.    ])

array([[ 0.6583,  0.2388, -0.2172, -0.68  ],
       [-0.1308, -0.2317,  0.8383, -0.4758],
       [-0.5472,  0.7996, -0.0049, -0.2474],
       [ 0.5   ,  0.5   ,  0.5   ,  0.5   ]])

In [460]:
beta_k = eigenvectors
n_lambda_k = eigenvalues

In [461]:
A = np.array([
    [10, 20, 30, 40, 50],
    [10, 20, 30, 40, 50],
])

b = np.array([5, 10]).reshape(-1, 1)

A/b

array([[ 2.,  4.,  6.,  8., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [462]:
alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)
alpha_k = alpha_k.T  # alpha values in cols
alpha_k
alpha_k.shape

C:\Users\k26ra\AppData\Local\Temp\ipykernel_5312\3259128272.py:1: RuntimeWarning: invalid value encountered in sqrt
  alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)


array([[ 0.0146, -0.0313, -0.2985,     nan],
       [ 0.0053, -0.0555,  0.4362,     nan],
       [-0.0048,  0.2008, -0.0027,     nan],
       [-0.0151, -0.114 , -0.135 ,     nan]])

(4, 4)

In [463]:
X.shape, alpha_k.shape
W_k = X @ alpha_k
W_k
W_k.shape

((10, 4), (4, 4))

array([[-0.046 ,  0.0793,  0.0597,     nan],
       [-0.0978,  0.1246,  0.1057,     nan],
       [-0.1697, -0.151 , -0.1348,     nan],
       [-0.201 ,  0.0687,  0.3992,     nan],
       [-0.2747,  0.2236, -0.2839,     nan],
       [-0.2956,  0.4038,  0.5958,     nan],
       [-0.3616, -0.413 ,  0.0752,     nan],
       [-0.4204, -0.6575,  0.0799,     nan],
       [-0.3944,  0.1526,  0.1969,     nan],
       [-0.5415,  0.3338, -0.5669,     nan]])

(10, 4)

In [464]:
# np.linalg.norm(W_k, axis=0)
W_k = W_k / np.linalg.norm(W_k, axis=0)
W_k

array([[-0.046 ,  0.0793,  0.0597,     nan],
       [-0.0978,  0.1246,  0.1057,     nan],
       [-0.1697, -0.151 , -0.1348,     nan],
       [-0.201 ,  0.0687,  0.3992,     nan],
       [-0.2747,  0.2236, -0.2839,     nan],
       [-0.2956,  0.4038,  0.5958,     nan],
       [-0.3616, -0.413 ,  0.0752,     nan],
       [-0.4204, -0.6575,  0.0799,     nan],
       [-0.3944,  0.1526,  0.1969,     nan],
       [-0.5415,  0.3338, -0.5669,     nan]])

# PCA main algo (C = XX' / n)

In [465]:
n = X.shape[1]
C = X @ X.T / n
C.shape

(10, 10)

In [466]:
eigenvalues, eigenvectors = np.linalg.eigh(C)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]
# eigenvalues = np.where(np.isclose(eigenvalues, 0), 0, eigenvalues)

eigenvalues[:4]
n_lambda_k / n

eigenvectors[:4].T
W_k

array([509.4989,   4.3592,   0.84  ,   0.    ])

array([509.4989,   4.3592,   0.84  ,  -0.    ])

array([[-0.046 , -0.0793, -0.0597, -0.9933],
       [-0.0978, -0.1246, -0.1057, -0.0109],
       [-0.1697,  0.151 ,  0.1348, -0.0158],
       [-0.201 , -0.0687, -0.3992,  0.0505],
       [-0.2747, -0.2236,  0.2839,  0.0188],
       [-0.2956, -0.4038, -0.5958,  0.0875],
       [-0.3616,  0.413 , -0.0752, -0.0135],
       [-0.4204,  0.6575, -0.0799, -0.0262],
       [-0.3944, -0.1526, -0.1969,  0.0324],
       [-0.5415, -0.3338,  0.5669,  0.021 ]])

array([[-0.046 ,  0.0793,  0.0597,     nan],
       [-0.0978,  0.1246,  0.1057,     nan],
       [-0.1697, -0.151 , -0.1348,     nan],
       [-0.201 ,  0.0687,  0.3992,     nan],
       [-0.2747,  0.2236, -0.2839,     nan],
       [-0.2956,  0.4038,  0.5958,     nan],
       [-0.3616, -0.413 ,  0.0752,     nan],
       [-0.4204, -0.6575,  0.0799,     nan],
       [-0.3944,  0.1526,  0.1969,     nan],
       [-0.5415,  0.3338, -0.5669,     nan]])

# chatgpt

In [467]:
C = (1 / X.shape[1]) * X @ X.T
eigenvalues, eigenvectors = np.linalg.eigh(C)
eigenvalues = eigenvalues[::-1]
eigenvectors = eigenvectors[:, ::-1]  # descending order

eigenvalues[:4]
eigenvectors[:, :4]

array([509.4989,   4.3592,   0.84  ,   0.    ])

array([[-0.046 , -0.0793, -0.0597, -0.9933],
       [-0.0978, -0.1246, -0.1057, -0.0109],
       [-0.1697,  0.151 ,  0.1348, -0.0158],
       [-0.201 , -0.0687, -0.3992,  0.0505],
       [-0.2747, -0.2236,  0.2839,  0.0188],
       [-0.2956, -0.4038, -0.5958,  0.0875],
       [-0.3616,  0.413 , -0.0752, -0.0135],
       [-0.4204,  0.6575, -0.0799, -0.0262],
       [-0.3944, -0.1526, -0.1969,  0.0324],
       [-0.5415, -0.3338,  0.5669,  0.021 ]])

In [468]:
K = (1 / X.shape[1]) * X.T @ X
eigenvalues, eigenvectors = np.linalg.eig(K)  # eig vs eigh
eigenvalues = eigenvalues[::-1]
eigenvectors = eigenvectors[:, ::-1]

# recover eigenvectors of c
eigenvectors_C = (X @ eigenvectors) / np.sqrt(eigenvalues)

# normalize each column (principal component)
eigenvectors_C /= np.linalg.norm(eigenvectors_C, axis=0)

eigenvectors_C[:, ::-1]  # cols reversed because .eig(K), not .eigh(K)

C:\Users\k26ra\AppData\Local\Temp\ipykernel_5312\2364078005.py:7: RuntimeWarning: invalid value encountered in sqrt
  eigenvectors_C = (X @ eigenvectors) / np.sqrt(eigenvalues)


array([[-0.046 ,  0.0793,  0.0597,     nan],
       [-0.0978,  0.1246,  0.1057,     nan],
       [-0.1697, -0.151 , -0.1348,     nan],
       [-0.201 ,  0.0687,  0.3992,     nan],
       [-0.2747,  0.2236, -0.2839,     nan],
       [-0.2956,  0.4038,  0.5958,     nan],
       [-0.3616, -0.413 ,  0.0752,     nan],
       [-0.4204, -0.6575,  0.0799,     nan],
       [-0.3944,  0.1526,  0.1969,     nan],
       [-0.5415,  0.3338, -0.5669,     nan]])