In [13]:
import numpy as np

In NumPy, the @ operator is used for matrix multiplication.

- When applied to 1D arrays, @ performs the dot product.
- When applied to 2D arrays, @ performs standard matrix multiplication.

In [14]:
a = np.array([1, 2, 3])  # vector in 1d
A = np.array([[1], [2], [3]])  # vector in 2d

a.shape
A.shape

(3,)

(3, 1)

In [15]:
A.T.shape, A.shape
A.T @ A  # 1x1

A.shape, A.T.shape
A @ A.T  # 3x3

((1, 3), (3, 1))

array([[14]])

((3, 1), (1, 3))

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a.shape
a.T.shape

a @ b
b @ a

(3,)

(3,)

np.int64(32)

np.int64(32)

In [17]:
a = np.array([1, 2, 3])
A = a.reshape(-1, 1)

a
a.shape

A
A.shape

array([1, 2, 3])

(3,)

array([[1],
       [2],
       [3]])

(3, 1)

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A.shape, B.shape

A @ B
B @ A
A @ B.T
A.T @ B

((2, 2), (2, 2))

array([[19, 22],
       [43, 50]])

array([[23, 34],
       [31, 46]])

array([[17, 23],
       [39, 53]])

array([[26, 30],
       [38, 44]])