# PA

In [1]:
import numpy as np

In [2]:
old = 100 * 3
new = 100 + 3

(1 - new / old) * 100

65.66666666666667

In [3]:
X = np.array([
    [0, 0],
    [3, 4],
    [6, 8],
    [1/5, 4/15]
])

w = np.array([3/5, 4/5]).reshape(-1, 1)

X.shape
w.shape

X @ w

(4, 2)

(2, 1)

array([[ 0.        ],
       [ 5.        ],
       [10.        ],
       [ 0.33333333]])

# GA

In [4]:
x = np.array([1, -1])
w = np.array([3, 3])
w = w / np.linalg.norm(w)

x_projected = (x.T @ w) * w
x_projected

residue = x - x_projected
residue

array([0., 0.])

array([ 1., -1.])

In [5]:
x = np.array([2, 5])
w = np.array([1, 1])
w = w / np.linalg.norm(w)

x_projected = x.T @ w * w

np.linalg.norm(x_projected)
x - x_projected
np.linalg.norm(x - x_projected)**2

np.float64(4.949747468305832)

array([-1.5,  1.5])

np.float64(4.499999999999999)

In [6]:
old = 1000 * 30
new = 1000 * 4 + (30 + 30 + 30 + 30)

(1 - new/old) * 100

86.26666666666667

In [7]:
X = np.array([
    [-1, 0],
    [-2, 0],
    [-3, 0],
    [-2, 1],

    [1, 0],
    [2, 0],
    [3, 0],
    [2, -1],
]).T

n = X.shape[1]
C = X @ X.T / n
C

array([[ 4.5 , -0.5 ],
       [-0.5 ,  0.25]])

In [8]:
w = np.array([-0.993, 0.115]).reshape(-1, 1)

X.shape, w.shape

coefficients = X.T @ w
np.mean(coefficients ** 2)  # variance along w

((2, 8), (2, 1))

np.float64(4.554721750000001)

In [9]:
eigenvalues = [3.2, 1.5, 0.2, 0.01, 0.001]
np.cumsum(eigenvalues) / np.sum(eigenvalues)

array([0.65159845, 0.95703523, 0.99776013, 0.99979638, 1.        ])