In [64]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

In [65]:
# np.random.seed(1)

# X = np.array([
#     [
#         (i * j) * (1 + np.random.uniform(-0.1, 0.1))  # ±10% noise
#         for j in range(1, 11)
#     ]
#     for i in range(1, 5)
# ]).T

# X
# X.shape  # d > n (can use alternate PCA algorithm, K = X'X)

In [66]:
X = np.array([[0.9834,  1.9677,  3.1804,  3.6787],
              [2.0881,  4.1482,  6.5619,  7.8738],
              [2.7001,  5.6453,  8.6642, 13.0989],
              [3.8419,  8.605, 12.4616, 16.1061],
              [4.6468,  9.0548, 16.1292, 20.7675],
              [5.5108, 12.4091, 19.4206, 23.1145],
              [6.5608, 13.7685, 19.2572, 29.0444],
              [7.7529, 16.1878, 21.7875, 34.1416],
              [8.8142, 16.7054, 25.2171, 32.5317],
              [10.0776, 18.7924, 32.2689, 42.0012]])
X.shape

(10, 4)

In [67]:
# X.mean(axis=1, keepdims=True)
X = X - X.mean(axis=1, keepdims=True)  # center the data
# X

# PCA alternate algo (K = X'X)

In [68]:
X.T.shape, X.shape
K = X.T @ X
K.shape  # K is n * n matrix

((4, 10), (10, 4))

(4, 4)

In [69]:
eigenvalues, eigenvectors = np.linalg.eigh(K)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]

eigenvalues
eigenvectors

array([2037.9971,   17.4367,    3.36  ,    0.    ])

array([[-0.6583, -0.2388,  0.2172,  0.68  ],
       [-0.1308, -0.2317,  0.8383, -0.4758],
       [ 0.5472, -0.7996,  0.0049,  0.2474],
       [-0.5   , -0.5   , -0.5   , -0.5   ]])

In [70]:
beta_k = eigenvectors
n_lambda_k = eigenvalues

In [71]:
A = np.array([
    [10, 20, 30, 40, 50],
    [10, 20, 30, 40, 50],
])

b = np.array([5, 10]).reshape(-1, 1)

A/b

array([[ 2.,  4.,  6.,  8., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [72]:
alpha_k = beta_k / np.sqrt(n_lambda_k).reshape(-1, 1)
alpha_k = alpha_k.T  # alpha values in cols
alpha_k
alpha_k.shape

array([[      -0.0146,       -0.0313,        0.2985, -2638673.1451],
       [      -0.0053,       -0.0555,       -0.4362, -2638673.1451],
       [       0.0048,        0.2008,        0.0027, -2638673.1451],
       [       0.0151,       -0.114 ,        0.135 , -2638673.1451]])

(4, 4)

In [73]:
X.shape, alpha_k.shape
W_k = X @ alpha_k
W_k
W_k.shape

((10, 4), (4, 4))

array([[ 0.046 ,  0.0793, -0.0597, -0.    ],
       [ 0.0978,  0.1246, -0.1057, -0.    ],
       [ 0.1697, -0.151 ,  0.1349,  0.    ],
       [ 0.201 ,  0.0687, -0.3992, -0.    ],
       [ 0.2747,  0.2236,  0.2839,  0.    ],
       [ 0.2956,  0.4038, -0.5957, -0.    ],
       [ 0.3616, -0.413 , -0.0752, -0.    ],
       [ 0.4204, -0.6575, -0.0799, -0.    ],
       [ 0.3944,  0.1526, -0.1969, -0.    ],
       [ 0.5415,  0.3338,  0.5669,  0.    ]])

(10, 4)

In [74]:
# np.linalg.norm(W_k, axis=0)
W_k = W_k / np.linalg.norm(W_k, axis=0)
W_k

array([[ 0.046 ,  0.0793, -0.0597, -0.0578],
       [ 0.0978,  0.1246, -0.1057, -0.11  ],
       [ 0.1697, -0.151 ,  0.1349,  0.1342],
       [ 0.201 ,  0.0687, -0.3992, -0.41  ],
       [ 0.2747,  0.2236,  0.2839,  0.243 ],
       [ 0.2956,  0.4038, -0.5957, -0.6243],
       [ 0.3616, -0.413 , -0.0752, -0.0732],
       [ 0.4204, -0.6575, -0.0799, -0.0552],
       [ 0.3944,  0.1526, -0.1969, -0.22  ],
       [ 0.5415,  0.3338,  0.5669,  0.5412]])

# PCA main algo (C = XX' / n)

In [75]:
n = X.shape[1]
C = X @ X.T / n
C.shape

(10, 10)

In [76]:
eigenvalues, eigenvectors = np.linalg.eigh(C)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors.T[sorted_indices]
# eigenvalues = np.where(np.isclose(eigenvalues, 0), 0, eigenvalues)

eigenvalues[:4]
n_lambda_k / n

eigenvectors[:4].T
W_k

array([509.4993,   4.3592,   0.84  ,   0.    ])

array([509.4993,   4.3592,   0.84  ,   0.    ])

array([[-0.046 , -0.0793, -0.0597, -0.1278],
       [-0.0978, -0.1246, -0.1057,  0.316 ],
       [-0.1697,  0.151 ,  0.1349, -0.0543],
       [-0.201 , -0.0687, -0.3992,  0.0578],
       [-0.2747, -0.2236,  0.2839, -0.7752],
       [-0.2956, -0.4038, -0.5957, -0.0887],
       [-0.3616,  0.413 , -0.0752,  0.256 ],
       [-0.4204,  0.6575, -0.0799, -0.2175],
       [-0.3944, -0.1526, -0.1969, -0.0078],
       [-0.5415, -0.3338,  0.5669,  0.3947]])

array([[ 0.046 ,  0.0793, -0.0597, -0.0578],
       [ 0.0978,  0.1246, -0.1057, -0.11  ],
       [ 0.1697, -0.151 ,  0.1349,  0.1342],
       [ 0.201 ,  0.0687, -0.3992, -0.41  ],
       [ 0.2747,  0.2236,  0.2839,  0.243 ],
       [ 0.2956,  0.4038, -0.5957, -0.6243],
       [ 0.3616, -0.413 , -0.0752, -0.0732],
       [ 0.4204, -0.6575, -0.0799, -0.0552],
       [ 0.3944,  0.1526, -0.1969, -0.22  ],
       [ 0.5415,  0.3338,  0.5669,  0.5412]])

# chatgpt

In [77]:
C = (1 / X.shape[1]) * X @ X.T
eigenvalues, eigenvectors = np.linalg.eigh(C)
eigenvalues = eigenvalues[::-1]
eigenvectors = eigenvectors[:, ::-1]  # descending order

eigenvalues[:4]
eigenvectors[:, :4]

array([509.4993,   4.3592,   0.84  ,   0.    ])

array([[-0.046 , -0.0793, -0.0597, -0.1278],
       [-0.0978, -0.1246, -0.1057,  0.316 ],
       [-0.1697,  0.151 ,  0.1349, -0.0543],
       [-0.201 , -0.0687, -0.3992,  0.0578],
       [-0.2747, -0.2236,  0.2839, -0.7752],
       [-0.2956, -0.4038, -0.5957, -0.0887],
       [-0.3616,  0.413 , -0.0752,  0.256 ],
       [-0.4204,  0.6575, -0.0799, -0.2175],
       [-0.3944, -0.1526, -0.1969, -0.0078],
       [-0.5415, -0.3338,  0.5669,  0.3947]])

In [78]:
K = (1 / X.shape[1]) * X.T @ X
eigenvalues, eigenvectors = np.linalg.eigh(K)  # eig vs eigh
eigenvalues = eigenvalues[::-1]
eigenvectors = eigenvectors[:, ::-1]

# recover eigenvectors of c
eigenvectors_C = (X @ eigenvectors) / np.sqrt(eigenvalues)

# normalize each column (principal component)
eigenvectors_C /= np.linalg.norm(eigenvectors_C, axis=0)

# eigenvectors_C[:, ::-1]  # cols reversed because .eig(K), not .eigh(K)
eigenvectors_C[:]

array([[ 0.046 ,  0.0793, -0.0597, -0.0595],
       [ 0.0978,  0.1246, -0.1057, -0.1138],
       [ 0.1697, -0.151 ,  0.1349,  0.1311],
       [ 0.201 ,  0.0687, -0.3992, -0.4105],
       [ 0.2747,  0.2236,  0.2839,  0.2415],
       [ 0.2956,  0.4038, -0.5957, -0.6279],
       [ 0.3616, -0.413 , -0.0752, -0.0828],
       [ 0.4204, -0.6575, -0.0799, -0.0552],
       [ 0.3944,  0.1526, -0.1969, -0.2139],
       [ 0.5415,  0.3338,  0.5669,  0.5382]])