In [63]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

np.set_printoptions(precision=4, suppress=True)

In [64]:
def unit(v):
  return v / np.linalg.norm(v)

In [65]:
# original 3D data
X = np.array([
    [1, 2.2, 1],
    [2, 5, 4],
    [3, 6.6, 1.5],
    [4, 9, -3],
    [5, 9.5, 2],
]).T

X

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 2.2,  5. ,  6.6,  9. ,  9.5],
       [ 1. ,  4. ,  1.5, -3. ,  2. ]])

In [66]:
# orthonormal basis (w1, w2, w3)
w1 = np.array([1, 0.5, 0.2])
w2 = np.cross(w1, [0, 0, 1])
w3 = np.cross(w1, w2)

w1 = unit(w1)
w2 = unit(w2)
w3 = unit(w3)

w1, w2, w3

(array([0.8805, 0.4402, 0.1761]),
 array([ 0.4472, -0.8944,  0.    ]),
 array([ 0.1575,  0.0787, -0.9844]))

In [67]:
c1 = X.T @ w1
c2 = X.T @ w2
c3 = X.T @ w3

In [68]:
proxies_w1 = w1.reshape(-1, 1) @ c1.reshape(1, -1)
proxies_w2 = w2.reshape(-1, 1) @ c2.reshape(1, -1)
proxies_w3 = w3.reshape(-1, 1) @ c3.reshape(1, -1)

In [69]:
X_reconstructed = proxies_w1 + proxies_w2 + proxies_w3

X
X_reconstructed
np.mean((X - X_reconstructed)**2)

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 2.2,  5. ,  6.6,  9. ,  9.5],
       [ 1. ,  4. ,  1.5, -3. ,  2. ]])

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 2.2,  5. ,  6.6,  9. ,  9.5],
       [ 1. ,  4. ,  1.5, -3. ,  2. ]])

np.float64(9.532069271420559e-32)

In [70]:
fig = go.Figure()

# original
_ = fig.add_trace(go.Scatter3d(
    x=X[0], y=X[1], z=X[2],
    mode='markers',
    name='Original',
    marker=dict(size=5)
))

# reconstructed
_ = fig.add_trace(go.Scatter3d(
    x=X_reconstructed[0], y=X_reconstructed[1], z=X_reconstructed[2],
    mode='markers',
    name='Reconstructed',
    marker=dict(size=10, symbol='cross', color='orange')
))

# basis lines
for w, name in zip([w1, w2, w3], ['w1', 'w2', 'w3']):
  _ = fig.add_trace(go.Scatter3d(
      x=[0, w[0]*5], y=[0, w[1]*5], z=[0, w[2]*5],
      mode='lines+text',
      name=name
  ))

fig.update_layout(
    scene=dict(aspectmode='cube'),
    title="3D Projection and Reconstruction"
)

# variance explained

In [71]:
v1 = np.var(c1)
v2 = np.var(c2)
v3 = np.var(c3)
total = v1 + v2 + v3

v1/total, v2/total, v3/total
np.cumsum([v1/total, v2/total, v3/total])

(np.float64(0.3689558249491451),
 np.float64(0.22043439716312052),
 np.float64(0.41060977788773434))

array([0.369 , 0.5894, 1.    ])