In [31]:
import numpy as np

In NumPy, the @ operator is used for matrix multiplication.

- When applied to 1D arrays, @ performs the dot product.
- When applied to 2D arrays, @ performs standard matrix multiplication.

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

a @ b,  b @ a

a @ b.T,  a.T @ b

np.int64(32)

(np.int64(32), np.int64(32))

(np.int64(32), np.int64(32))

In [49]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.array([4, 5, 6]).reshape(-1, 1)

a.shape, b.shape

a.T @ b
a @ b.T

((3, 1), (3, 1))

array([[32]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [50]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A.shape, B.shape

A @ B
B @ A
A @ B.T
A.T @ B

((2, 2), (2, 2))

array([[19, 22],
       [43, 50]])

array([[23, 34],
       [31, 46]])

array([[17, 23],
       [39, 53]])

array([[26, 30],
       [38, 44]])