In [1]:
import numpy as np

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [27]:
np.dot(a, b)
a @ b
b @ a

np.int64(32)

np.int64(32)

np.int64(32)

In [26]:
np.outer(a, b)
np.outer(b, a)

np.inner(a, b)
np.inner(b, a)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

np.int64(32)

np.int64(32)

In [36]:
A = a.reshape(-1, 1)
B = b.reshape(-1, 1)

A
A.shape
B.shape

array([[1],
       [2],
       [3]])

(3, 1)

(3, 1)

In [ ]:
A.T @ B
A @ B.T

array([[32]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [46]:
A.shape
B.shape

np.inner(A, B)
np.outer(A, B)

(3, 1)

(3, 1)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [54]:
U = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
])

V = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [4, 5, 6],
])

np.inner(U, V)
np.outer(U, V)

array([[32, 32, 32],
       [32, 32, 32],
       [32, 32, 32]])

array([[ 4,  5,  6,  4,  5,  6,  4,  5,  6],
       [ 8, 10, 12,  8, 10, 12,  8, 10, 12],
       [12, 15, 18, 12, 15, 18, 12, 15, 18],
       [ 4,  5,  6,  4,  5,  6,  4,  5,  6],
       [ 8, 10, 12,  8, 10, 12,  8, 10, 12],
       [12, 15, 18, 12, 15, 18, 12, 15, 18],
       [ 4,  5,  6,  4,  5,  6,  4,  5,  6],
       [ 8, 10, 12,  8, 10, 12,  8, 10, 12],
       [12, 15, 18, 12, 15, 18, 12, 15, 18]])

In [49]:
U.shape
V.shape

U @ V
V @ U

(3, 3)

(3, 3)

array([[24, 30, 36],
       [24, 30, 36],
       [24, 30, 36]])

array([[15, 30, 45],
       [15, 30, 45],
       [15, 30, 45]])